### ISSUE TITLE
Animation Triggers Twice upon Mounting in Safari and Ionic App

### ISSUE THREAD

**Issue by jon-pruessmeier** [setaman/vue-ellipse-progress#210]
**Describe the bug**
The component triggers animations twice upon mounting when using Safari or in an Ionic app which uses Safari as the browser. This issue doesn't occur when using Chrome, where the animation runs only once as expected.

**To Reproduce**
I've built a sample app that demonstrates the issue. The app includes Capacitor/Ionic, so the base app can be launched in an iOS emulator. However, the problem can also be seen simply by launching the app in Safari.

1. Launch the app in Safari or in an iOS emulator.
2. Observe the animations upon mounting.

https://github.com/jon-pruessmeier/vue-ellipse-animates-twice-safari

**Expected behavior**
I expect the animation to be run once upon mounting, similar to the behavior in Chrome.

**Screenshots**

https://github.com/setaman/vue-ellipse-progress/assets/83428138/c2485a43-36d8-410e-9f49-021329f83422

https://github.com/setaman/vue-ellipse-progress/assets/83428138/185d78d8-6415-491b-994e-ffea1e954534

**Desktop:**

- OS: MacOS 13.5
- Browser: Safari 
- Version: 16.5 

**Smartphone:**

- iOS emulators and devices in general

**Plugin Version:** v2.1.1

**Additional context**
I haven't been able to identify the root cause of this issue. Possibly, certain CSS properties are interpreted differently, or not at all, in Safari? I tested this issue with Node 19.4.0. Any help in diagnosing and resolving this issue would be greatly appreciated.

**Comment by setaman** [comment]
Hallo, @jon-pruessmeier thanks for the detailed issue explanation, appreciate that!

I confirm the bug, also in Edge browser on IOS. It's very likely that this is caused by the Safari browser (and Apple's systems in general). I've had to fight with it several times. CSS implementation on IOS/MacOS even in Chrome may differ a lot.

I'll try to investigate the issue as soon as possible. Sadly i have no Apple device where i can debug, so your assistance is also much appreciated. Until then i only can suggest you to disable the animation, you can play with the settings here: https://setaman.github.io/vue-ellipse-progress-docs/guide/options/animation.html

**Comment by setaman** [comment]
My findings so far:

- MacOS 13, Firefox/Chrome/edge - works without any issue, tested on [https://saucelabs.com/]( https://saucelabs.com/)
- MacOS 13, Safari 16 - animation triggered twice
- IPhone 12, Safari/Edge - animation triggered twice
- https://github.com/reactjs/react-transition-group/issues/631

So the old good Safari Browser (and probably older Apple systems) trigger the **transition** right after the initial animation. Removing the transition would fixe the issue, but dropping a smooth user experience just because of one buggy browser isn't an option. Applying `animation-fill-mode: forwards` would also fix the problem, but disable the transition. The solution could be to disable transition while playing the animation.
