### ISSUE TITLE
The dot is not working on IOS device

### ISSUE THREAD

**Issue by shiyu3169** [setaman/vue-ellipse-progress#82]
The dot is not moving on IOS device for me. 
Device: iPhone XS,
Browser: Chrome

**Comment by shiyu3169** [comment]
Also, I've noticed the dot is not always stay at the end of the progress bar (probably only when progress bar is not at constant speed).

**Comment by setaman** [comment]
I finally had time to check it on an emulator. Thanks for the hint. I confirm this issue in Chromium on an IOS device. There must be a problem with the `foreignObject` in the browser. I don't have an IOS device, which makes debugging very hard for me. So any help is very welcome!

I think the easiest way for me will be to implement this without `foreignObject`. Should be fixed in upcoming v1.3.0

**Comment by setaman** [comment]
fix immediately available in v1.3.0-beta.6

```
npm i vue-ellipse-progress@1.3.0-beta.6
```
